#hello deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
  namespace: tiacourses
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: hello-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app-container
        image: ptimti/tiacloud:v2
        ports:
        - containerPort: 8080
